DefaultRuntimeDir ${APACHE_RUN_DIR}
PidFile ${APACHE_PID_FILE}

# ---------------------------------------------------------------------
Timeout 300
# Enable KeepAlive to allow multiple requests per TCP connection.
KeepAlive On
# Time (in seconds) for the server to wait for a new request before closing the connection.
KeepAliveTimeout 5
# Maximum requests per connection.
MaxKeepAliveRequests 8
# ---------------------------------------------------------------------

# ---------------------------------------------------------------------
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}
# ---------------------------------------------------------------------

# ---------------------------------------------------------------------
HostnameLookups Off

ErrorLog /proc/self/fd/2
LogLevel info
# ---------------------------------------------------------------------

# Include module configuration:
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

# ---------------------------------------------------------------------
<Directory />
	Options FollowSymLinks
	AllowOverride None
	Require all denied
</Directory>

<Directory /usr/share>
	AllowOverride None
	Require all granted
</Directory>

AccessFileName .htaccess

<FilesMatch "^\.ht">
	Require all denied
</FilesMatch>
# ---------------------------------------------------------------------

# ---------------------------------------------------------------------
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
# ---------------------------------------------------------------------

# ---------------------------------------------------------------------
# Timeout Settings for protection against DoS attacks.
RequestReadTimeout handshake=5 header=10-30,MinRate=500 body=5,MinRate=1000
# ---------------------------------------------------------------------

# Defines the maximum size, in bytes, of the request line allowed by the server.
LimitRequestLine 131072

Listen 80

# ---------------------------------------------------------------------
ServerTokens Prod
ServerSignature Off
TraceEnable Off
# ---------------------------------------------------------------------

<FilesMatch \.php$>
	SetHandler application/x-httpd-php
</FilesMatch>

DirectoryIndex disabled
DirectoryIndex index.php index.html

<Directory /var/www/>
	Options -Indexes +FollowSymLinks
	AllowOverride All	
</Directory>

<VirtualHost *:80>
	ServerAdmin noc@uptech.com.br
	DocumentRoot /var/www/html

	RemoteIPHeader X-Forwarded-For
	RemoteIPInternalProxy 10.5.0.0/16

	<Location "/">
		Require expr "%{CONN_REMOTE_ADDR} -ipmatch '10.5.0.0/16'"
	</Location>

	<Location "/.freepbx-known/">
		Require all granted
	</Location>

	<Location "/.well-known/acme-challenge/">
		Require all granted
	</Location>
</VirtualHost>
