[transport-udpv6]
type=transport
protocol=udp
bind=[::]:5060
allow_reload=no
tos=cs3
cos=3

# [transport-udpv6-tls]
# type=transport
# protocol=tls
# bind=[::]:5061
# ca_list_file=/etc/ssl/certs/ca-certificates.crt
# cert_file=/etc/asterisk/keys/default.crt
# priv_key_file=/etc/asterisk/keys/default.key
# method=tlsv1_3
# verify_client=yes
# verify_server=yes
# allow_reload=no
# tos=cs3
# cos=3
